# Generated by Django 4.1.7 on 2023-03-28 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_jobdescription_jobtitle_applicant"),
        ("jobs", "0002_person"),
    ]

    operations = []
