# Generated by Django 4.1.7 on 2023-03-28 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_merge_20230328_1541"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
